// Curated universe of instruments available to retail investors via
// TBC Bank Georgia / TBC Capital brokerage (US, UK & EU listings).
// Bond exposure is represented by liquid bond ETFs — same access TBC offers.

export const CATALOG = [
  // Georgian banks listed in London
  { sym: "TBCG.L", name: "TBC Bank Group PLC", cat: "stock", note: "LSE · Parent of TBC Bank Georgia", ccy: "GBP" },
  { sym: "BGEO.L", name: "Bank of Georgia Group", cat: "stock", note: "LSE · Georgian banking peer", ccy: "GBP" },
  // US stocks
  { sym: "AAPL", name: "Apple Inc.", cat: "stock", note: "NASDAQ", ccy: "USD" },
  { sym: "MSFT", name: "Microsoft Corp.", cat: "stock", note: "NASDAQ", ccy: "USD" },
  { sym: "NVDA", name: "NVIDIA Corp.", cat: "stock", note: "NASDAQ", ccy: "USD" },
  { sym: "GOOGL", name: "Alphabet Inc.", cat: "stock", note: "NASDAQ", ccy: "USD" },
  { sym: "AMZN", name: "Amazon.com Inc.", cat: "stock", note: "NASDAQ", ccy: "USD" },
  { sym: "META", name: "Meta Platforms", cat: "stock", note: "NASDAQ", ccy: "USD" },
  { sym: "TSLA", name: "Tesla Inc.", cat: "stock", note: "NASDAQ", ccy: "USD" },
  { sym: "JPM", name: "JPMorgan Chase", cat: "stock", note: "NYSE", ccy: "USD" },
  { sym: "V", name: "Visa Inc.", cat: "stock", note: "NYSE", ccy: "USD" },
  { sym: "KO", name: "Coca-Cola Co.", cat: "stock", note: "NYSE", ccy: "USD" },
  { sym: "WMT", name: "Walmart Inc.", cat: "stock", note: "NYSE", ccy: "USD" },
  // Equity ETFs
  { sym: "VTI", name: "Vanguard Total Stock Market", cat: "etf", note: "US total market", ccy: "USD" },
  { sym: "VOO", name: "Vanguard S&P 500", cat: "etf", note: "S&P 500", ccy: "USD" },
  { sym: "SPY", name: "SPDR S&P 500 Trust", cat: "etf", note: "S&P 500", ccy: "USD" },
  { sym: "QQQ", name: "Invesco QQQ Trust", cat: "etf", note: "Nasdaq-100", ccy: "USD" },
  { sym: "VEA", name: "Vanguard Developed Markets", cat: "etf", note: "Ex-US developed", ccy: "USD" },
  { sym: "VWO", name: "Vanguard Emerging Markets", cat: "etf", note: "Emerging markets", ccy: "USD" },
  { sym: "VXUS", name: "Vanguard Total Intl Stock", cat: "etf", note: "Ex-US total", ccy: "USD" },
  { sym: "VWRA.L", name: "Vanguard FTSE All-World (Acc)", cat: "etf", note: "LSE · Accumulating", ccy: "USD" },
  { sym: "CSPX.L", name: "iShares Core S&P 500", cat: "etf", note: "LSE · UCITS", ccy: "USD" },
  { sym: "EIMI.L", name: "iShares Core MSCI EM IMI", cat: "etf", note: "LSE · UCITS", ccy: "USD" },
  // Bond ETFs
  { sym: "BND", name: "Vanguard Total Bond Market", cat: "bond", note: "US aggregate bonds", ccy: "USD" },
  { sym: "AGG", name: "iShares Core US Aggregate", cat: "bond", note: "US aggregate bonds", ccy: "USD" },
  { sym: "IEF", name: "iShares 7-10Y Treasury", cat: "bond", note: "US Treasuries", ccy: "USD" },
  { sym: "TLT", name: "iShares 20+Y Treasury", cat: "bond", note: "Long US Treasuries", ccy: "USD" },
  { sym: "SHY", name: "iShares 1-3Y Treasury", cat: "bond", note: "Short US Treasuries", ccy: "USD" },
  { sym: "LQD", name: "iShares iBoxx Inv Grade", cat: "bond", note: "Corporate bonds", ccy: "USD" },
  { sym: "HYG", name: "iShares High Yield Corp", cat: "bond", note: "High yield", ccy: "USD" },
  { sym: "EMB", name: "iShares JPM USD EM Bond", cat: "bond", note: "EM sovereigns", ccy: "USD" },
  { sym: "VWOB", name: "Vanguard EM Gov Bond USD", cat: "bond", note: "EM government", ccy: "USD" },
  { sym: "BNDX", name: "Vanguard Total Intl Bond", cat: "bond", note: "Ex-US bonds (hedged)", ccy: "USD" },
  // Futures (CME/CBOT continuous front contracts)
  { sym: "ES=F", name: "S&P 500 E-mini Future", cat: "futures", note: "CME · equity index", ccy: "USD" },
  { sym: "NQ=F", name: "Nasdaq 100 E-mini Future", cat: "futures", note: "CME · equity index", ccy: "USD" },
  { sym: "YM=F", name: "Dow Jones E-mini Future", cat: "futures", note: "CBOT · equity index", ccy: "USD" },
  { sym: "RTY=F", name: "Russell 2000 Future", cat: "futures", note: "CME · small caps", ccy: "USD" },
  { sym: "CL=F", name: "Crude Oil WTI Future", cat: "futures", note: "NYMEX · energy", ccy: "USD" },
  { sym: "BZ=F", name: "Brent Crude Future", cat: "futures", note: "NYMEX · energy", ccy: "USD" },
  { sym: "NG=F", name: "Natural Gas Future", cat: "futures", note: "NYMEX · energy", ccy: "USD" },
  { sym: "GC=F", name: "Gold Future", cat: "futures", note: "COMEX · metals", ccy: "USD" },
  { sym: "SI=F", name: "Silver Future", cat: "futures", note: "COMEX · metals", ccy: "USD" },
  { sym: "HG=F", name: "Copper Future", cat: "futures", note: "COMEX · metals", ccy: "USD" },
  { sym: "ZN=F", name: "10-Year T-Note Future", cat: "futures", note: "CBOT · rates", ccy: "USD" },
  { sym: "ZB=F", name: "30-Year T-Bond Future", cat: "futures", note: "CBOT · rates", ccy: "USD" },
  { sym: "ZC=F", name: "Corn Future", cat: "futures", note: "CBOT · agriculture", ccy: "USD" },
  { sym: "BTC=F", name: "Bitcoin Future (CME)", cat: "futures", note: "CME · crypto", ccy: "USD" },
  // Crypto (USD pairs, 24/7)
  { sym: "BTC-USD", name: "Bitcoin", cat: "crypto", note: "24/7 · store of value", ccy: "USD" },
  { sym: "ETH-USD", name: "Ethereum", cat: "crypto", note: "24/7 · smart contracts", ccy: "USD" },
  { sym: "SOL-USD", name: "Solana", cat: "crypto", note: "24/7 · high throughput", ccy: "USD" },
  { sym: "XRP-USD", name: "XRP", cat: "crypto", note: "24/7 · payments", ccy: "USD" },
  { sym: "BNB-USD", name: "BNB", cat: "crypto", note: "24/7 · exchange token", ccy: "USD" },
  { sym: "ADA-USD", name: "Cardano", cat: "crypto", note: "24/7 · L1", ccy: "USD" },
  { sym: "DOGE-USD", name: "Dogecoin", cat: "crypto", note: "24/7 · meme", ccy: "USD" },
  { sym: "AVAX-USD", name: "Avalanche", cat: "crypto", note: "24/7 · L1", ccy: "USD" },
  { sym: "LINK-USD", name: "Chainlink", cat: "crypto", note: "24/7 · oracles", ccy: "USD" },
  { sym: "LTC-USD", name: "Litecoin", cat: "crypto", note: "24/7 · payments", ccy: "USD" },
  // Forex majors + crosses
  { sym: "EURUSD=X", name: "EUR / USD", cat: "forex", note: "major · 24/5", ccy: "USD" },
  { sym: "GBPUSD=X", name: "GBP / USD", cat: "forex", note: "major · 24/5", ccy: "USD" },
  { sym: "USDJPY=X", name: "USD / JPY", cat: "forex", note: "major · 24/5", ccy: "JPY" },
  { sym: "USDCHF=X", name: "USD / CHF", cat: "forex", note: "major · 24/5", ccy: "CHF" },
  { sym: "AUDUSD=X", name: "AUD / USD", cat: "forex", note: "commodity $ · 24/5", ccy: "USD" },
  { sym: "USDCAD=X", name: "USD / CAD", cat: "forex", note: "commodity $ · 24/5", ccy: "CAD" },
  { sym: "NZDUSD=X", name: "NZD / USD", cat: "forex", note: "commodity $ · 24/5", ccy: "USD" },
  { sym: "EURGBP=X", name: "EUR / GBP", cat: "forex", note: "cross · 24/5", ccy: "GBP" },
  { sym: "EURJPY=X", name: "EUR / JPY", cat: "forex", note: "cross · 24/5", ccy: "JPY" },
  { sym: "GBPJPY=X", name: "GBP / JPY", cat: "forex", note: "cross · 24/5", ccy: "JPY" },
  // World indices
  { sym: "^GSPC", name: "S&P 500", cat: "index", note: "US · large cap", ccy: "USD" },
  { sym: "^IXIC", name: "Nasdaq Composite", cat: "index", note: "US · tech", ccy: "USD" },
  { sym: "^DJI", name: "Dow Jones 30", cat: "index", note: "US · blue chips", ccy: "USD" },
  { sym: "^RUT", name: "Russell 2000", cat: "index", note: "US · small cap", ccy: "USD" },
  { sym: "^VIX", name: "CBOE Volatility Index", cat: "index", note: "US · fear gauge", ccy: "USD" },
  { sym: "^FTSE", name: "FTSE 100", cat: "index", note: "UK", ccy: "GBP" },
  { sym: "^GDAXI", name: "DAX 40", cat: "index", note: "Germany", ccy: "EUR" },
  { sym: "^FCHI", name: "CAC 40", cat: "index", note: "France", ccy: "EUR" },
  { sym: "^STOXX50E", name: "Euro Stoxx 50", cat: "index", note: "Eurozone", ccy: "EUR" },
  { sym: "^NSEI", name: "Nifty 50", cat: "index", note: "India", ccy: "INR" },
  { sym: "^BSESN", name: "Sensex", cat: "index", note: "India · Bombay", ccy: "INR" },
  { sym: "^HSI", name: "Hang Seng", cat: "index", note: "Hong Kong", ccy: "HKD" },
  { sym: "^N225", name: "Nikkei 225", cat: "index", note: "Japan", ccy: "JPY" },
  { sym: "^AXJO", name: "ASX 200", cat: "index", note: "Australia", ccy: "AUD" },
  { sym: "^GSPTSE", name: "TSX Composite", cat: "index", note: "Canada", ccy: "CAD" },
  { sym: "^BVSP", name: "Bovespa", cat: "index", note: "Brazil", ccy: "BRL" },
  { sym: "^TA125.TA", name: "Tel Aviv 125", cat: "index", note: "Israel", ccy: "ILS" },
];

export const CATEGORY_LABELS = { stock: "Stocks", etf: "ETFs", bond: "Bonds", futures: "Futures", crypto: "Crypto", forex: "Forex", index: "Indices" };
